Enable compiling MPI 2 or MPI 3 support, with YVERSION environment variable to control at configuration

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -12,11 +12,13 @@ function errorIfEmpty {
 
 function showUsage {
     echo "./configure -i <install prefix>"
-    echo "Required environment variables to build YogiMPI: "
+    echo "* Required environment variables to build YogiMPI: "
     echo "YCC - Serial C compiler to use"
     echo "YCXX - Serial C++ compiler to use"
     echo "YF90 - Serial Fortran compiler to use"
     echo "YMPICXX - Parallel C++ compiler wrapper"
+    echo "* Optional environment variables: "
+    echo "YVERSION - Version of MPI to support (2 or 3, default is 3)"
     exit 0
 }
 
@@ -66,6 +68,22 @@ else
     fortranCompiler=$YF90
 fi
 
+if [[ ! -z $YVERSION ]]; then
+    if [[ $YVERSION == "3" ]]; then
+        echo "Enabling MPI 3 support in YogiMPI."
+        mpiVersion=3
+    elif [[ $YVERSION == "2" ]]; then
+        echo "Enabling MPI 2 support in YogiMPI."
+        mpiVersion=2
+    else
+        echo "Unrecognized MPI version $YVERSION."
+        exit 1
+    fi
+else
+    echo "Default MPI 3 support enabled."
+    mpiVersion=3
+fi
+
 mpiCXX=$YMPICXX
 
 # Hardcode this value for now.
@@ -102,6 +120,7 @@ sed -e "s|@INSTALLDIR@|${installDir}|g" \
     -e "s|@F90@|${fortranCompiler}|g" \
     -e "s|@LIBEXTENSION@|${libraryExtension}|g" \
     -e "s|@FCOMPFLAGS@|${fFlags}|g" \
+    -e "s|@MPIVERSION@|${mpiVersion}|g" \
     Make.flags.in > Make.flags
 
 sed -e "s|@INSTALLDIR@|${installDir}|g" \
