First pass at python3 compatability.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -24,6 +24,23 @@ function showUsage {
     exit 0
 }
 
+# Use python 2 if it works, otherwise use python 3
+_python=""
+python -c "x=1" > /dev/null 2>&1
+if [[ "$?" == "0" ]]; then
+    _python="python"
+    echo "Setting up with Python 2."
+else
+    python3 -c "x=1" > /dev/null 2>&1
+    if [[ "$?" == "0" ]]; then
+        _python="python3"
+        echo "Setting up with Python 3."
+    else
+        echo "Cannot detect working version of python"
+        exit 1
+    fi
+fi
+
 installDir=""
 
 while getopts ":i:h" opt; do
@@ -56,7 +73,7 @@ if [[ ! -z $YDEBUG ]]; then
 fi
 
 if [[ ! -z $YFAMILY ]]; then
-    if [[ $YFAMILY == "intel" ]]; then 
+    if [[ $YFAMILY == "intel" ]]; then
         echo "Using Intel compiler family defaults for Yogi."
         cCompiler=icc
         cxxCompiler=icpc
@@ -130,7 +147,8 @@ if [[ ${installDir} == "" ]]; then
     exit 1
 fi
 
-sed -e "s|@INSTALLDIR@|${installDir}|g" \
+sed -e "s|@PYTHON@|${_python}|g" \
+    -e "s|@INSTALLDIR@|${installDir}|g" \
     -e "s|@MPICXX@|${mpiCXX}|g" \
     -e "s|@CC@|${cCompiler}|g" \
     -e "s|@SERIALC@|${cCompiler}|g" \
@@ -146,24 +164,28 @@ sed -e "s|@INSTALLDIR@|${installDir}|g" \
     -e "s|@CALLMPI@|${callMPI}|g" \
     -e "s|@LIBEXTENSION@|${libraryExtension}|g" \
     -e "s|@LIBPATHVAR@|${libraryPathVar}|g" \
-    test/testRunner.sh.in > test/testRunner.sh 
+    test/testRunner.sh.in > test/testRunner.sh
 
 # This doesn't get installed, so keep it locally.
 chmod 750 test/testRunner.sh
 
 sed -e "s|@INSTALLDIR@|${installDir}|g" \
+    -e "s|@PYTHONCMD@|${_python}|g" \
     -e "s|@SERIALCCOMPILER@|${cCompiler}|g" \
     wrapper/mpicc.in > wrapper/mpicc
 
 sed -e "s|@INSTALLDIR@|${installDir}|g" \
+    -e "s|@PYTHONCMD@|${_python}|g" \
     -e "s|@SERIALCXXCOMPILER@|${cxxCompiler}|g" \
     wrapper/mpicxx.in > wrapper/mpicxx
 
 sed -e "s|@INSTALLDIR@|${installDir}|g" \
+    -e "s|@PYTHONCMD@|${_python}|g" \
     -e "s|@SERIALFORTRANCOMPILER@|${fortranCompiler}|g" \
     wrapper/mpif90.in > wrapper/mpif90
 
 sed -e "s|@INSTALLDIR@|${installDir}|g" \
+    -e "s|@PYTHONCMD@|${_python}|g" \
     -e "s|@SERIALFORTRANCOMPILER@|${fortranCompiler}|g" \
     wrapper/mpif77.in > wrapper/mpif77
 
@@ -174,13 +196,13 @@ sed -e "s|@INSTALLDIR@|${installDir}|g" \
 sed -e "s|@INSTALLDIR@|${installDir}|g" \
     -e "s|@LIBPATHVAR@|${libraryPathVar}|g" \
     etc/yogimpi.bashrc.in > etc/yogimpi.bashrc
-    
+
 sed -e "s|@INSTALLDIR@|${installDir}|g" \
     -e "s|@LIBPATHVAR@|${libraryPathVar}|g" \
     etc/yogimpi.cshrc.in > etc/yogimpi.cshrc
 
 cd wrapper
-python configure_wrapper.py
+$_python configure_wrapper.py
 cd ..
 
 echo "Type make to build YogiMPI."
